/**
 * Mapa de nombres de equipos en español.
 * Las claves son los nombres en inglés tal como vienen de football-data.org.
 */
const TEAM_NAMES_ES: Record<string, string> = {
  // Sudamérica
  Argentina: "Argentina",
  Brazil: "Brasil",
  Uruguay: "Uruguay",
  Colombia: "Colombia",
  Ecuador: "Ecuador",
  Venezuela: "Venezuela",
  Peru: "Perú",
  Paraguay: "Paraguay",
  Bolivia: "Bolivia",
  Chile: "Chile",

  // Europa
  France: "Francia",
  Germany: "Alemania",
  Spain: "España",
  Portugal: "Portugal",
  England: "Inglaterra",
  Netherlands: "Países Bajos",
  Italy: "Italia",
  Belgium: "Bélgica",
  Switzerland: "Suiza",
  Croatia: "Croacia",
  Denmark: "Dinamarca",
  Serbia: "Serbia",
  Poland: "Polonia",
  Turkey: "Türkiye",
  Scotland: "Escocia",
  Austria: "Austria",
  Ukraine: "Ucrania",
  Hungary: "Hungría",
  Romania: "Rumanía",
  Slovakia: "Eslovaquia",
  Slovenia: "Eslovenia",
  Albania: "Albania",
  Georgia: "Georgia",
  Greece: "Grecia",
  Czechia: "Chequia",
  "Czech Republic": "República Checa",
  Norway: "Noruega",
  Sweden: "Suecia",
  Finland: "Finlandia",
  Wales: "Gales",
  "Northern Ireland": "Irlanda del Norte",
  Ireland: "Irlanda",
  Israel: "Israel",
  "Bosnia and Herzegovina": "Bosnia y Herzegovina",
  Kosovo: "Kosovo",
  "North Macedonia": "Macedonia del Norte",
  Montenegro: "Montenegro",
  Luxembourg: "Luxemburgo",
  Iceland: "Islandia",

  // Norteamérica y Caribe
  "United States": "Estados Unidos",
  Mexico: "México",
  Canada: "Canadá",
  Honduras: "Honduras",
  Panama: "Panamá",
  "Costa Rica": "Costa Rica",
  Jamaica: "Jamaica",
  Guatemala: "Guatemala",
  Haiti: "Haití",
  "El Salvador": "El Salvador",
  "Trinidad and Tobago": "Trinidad y Tobago",
  Cuba: "Cuba",

  // África
  Morocco: "Marruecos",
  Senegal: "Senegal",
  Ghana: "Ghana",
  Cameroon: "Camerún",
  "Ivory Coast": "Costa de Marfil",
  "Côte d'Ivoire": "Costa de Marfil",
  Nigeria: "Nigeria",
  Egypt: "Egipto",
  "South Africa": "Sudáfrica",
  Algeria: "Argelia",
  Tunisia: "Túnez",
  Mali: "Malí",
  "DR Congo": "RD Congo",
  Congo: "Congo",
  Angola: "Angola",
  "Cape Verde": "Cabo Verde",
  Mozambique: "Mozambique",
  Namibia: "Namibia",
  Tanzania: "Tanzania",
  Uganda: "Uganda",
  Zimbabwe: "Zimbabue",
  Zambia: "Zambia",
  Guinea: "Guinea",
  "Burkina Faso": "Burkina Faso",
  Libya: "Libia",
  Sudan: "Sudán",
  Ethiopia: "Etiopía",
  Kenya: "Kenia",
  Rwanda: "Ruanda",
  Benin: "Benín",
  Gabon: "Gabón",
  Mauritania: "Mauritania",
  "Equatorial Guinea": "Guinea Ecuatorial",
  Niger: "Níger",
  Chad: "Chad",
  Togo: "Togo",
  Comoros: "Comoras",
  "Sierra Leone": "Sierra Leona",
  Gambia: "Gambia",
  Liberia: "Liberia",
  "Guinea-Bissau": "Guinea-Bisáu",

  // Asia
  Japan: "Japón",
  "South Korea": "Corea del Sur",
  "Korea Republic": "Corea del Sur",
  Australia: "Australia",
  "Saudi Arabia": "Arabia Saudita",
  Iran: "Irán",
  Qatar: "Catar",
  Iraq: "Irak",
  Indonesia: "Indonesia",
  China: "China",
  "New Zealand": "Nueva Zelanda",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  Jordan: "Jordania",
  Bahrain: "Baréin",
  Kuwait: "Kuwait",
  Oman: "Omán",
  Palestine: "Palestina",
  Syria: "Siria",
  Uzbekistan: "Uzbekistán",
  Kazakhstan: "Kazajistán",
  Philippines: "Filipinas",
  Thailand: "Tailandia",
  Malaysia: "Malasia",
  Vietnam: "Vietnam",
  India: "India",
};

/**
 * Devuelve el nombre del equipo en español.
 * Si no hay traducción, devuelve el nombre original.
 */
export function teamName(name: string): string {
  return TEAM_NAMES_ES[name] ?? name;
}
